### ISSUE TITLE
Enable travis and appveyor

### ISSUE THREAD

**Issue by davidanthoff** [ExpandingMan/Arrow.jl#15]

**Comment by ExpandingMan** [comment]
I think I have done this with Travis?  I'm not sure, I'm going to have to read up on how to enable that.  Also need to update the yaml at least for 0.7.

**Comment by davidanthoff** [comment]
I don't think so, it doesn't show any results from any CI runs and https://travis-ci.org/ExpandingMan/Arrow.jl doesn't exist.

It really is very simple: just head over to https://travis-ci.org/, login with your github account, click on the + on the left and select this repo here from the list and switch the on-off button over. That is it. Appveyor essentially the same story.

Both config files in this repo look fine, I think everything should just work if you switch things on.

**Comment by ExpandingMan** [comment]
Ok, they seem to be up.  Will re-open this issue if there seems to be a problem.
