### ISSUE TITLE
Workflow suggestion: never commit to ``master``, always go through a PR

### ISSUE THREAD

**Issue by davidanthoff** [ExpandingMan/Arrow.jl#33]
Would it be possible to adopt a workflow here where no one ever commits to ``master``, but every change goes through a PR? That would make it much easier for downstream users like myself to follow what is going on.

**Comment by ExpandingMan** [comment]
Sure, that's fair.  I may still merge very quickly if it is important bug fixes like the last commit, but having the PR is good for documentation purposes.

**Comment by davidanthoff** [comment]
Yes, that would be perfect! No need to keep them open long, it simply makes it easier to follow. We use the same model for VegaLite.jl, I often open a PR and merge it right away, but it leaves a more easily digested trail of what has changed.
