### ISSUE TITLE
Feature request: add `isless` function to compare two `Datestamp`s

### ISSUE THREAD

**Issue by metanoid** [ExpandingMan/Arrow.jl#46]
I ran into an issue where I could not find the `minimum` or `maximum` of an array of `Arrow.Datestamp` data, because these two functions require the existence of an `isless` function.

To reproduce:
```julia
import Arrow
import Dates
day1 = Arrow.Datestamp(Dates.today())
day2 = Arrow.Datestamp(Dates.today() + Dates.Day(1))
first_day = minimum(day1, day2)
```

Expected behaviour: returns `day1` value
Actual behaviour: Error message : `ERROR: MethodError: no method matching minimum(::Datestamp, ::Datestamp)`
Request: export `isless`, `minimum`, and `maximum` functions from `Arrow.jl` which can handle `Datestamp`s

What I tried:
I tried making my own `isless` function:
```julia
Base.isless(a::Datestamp, b::Datestamp) = isless(a.value, b.value)
```

However, this just leads to the new error message: `ERROR: MethodError: no method matching minimum(::Datestamp, ::Datestamp)`

**Comment by ExpandingMan** [comment]
On current master, the intention is that the Arrow time types should always be converted to Julia `Dates` types using `convert`.  This is of course not ideal.  Ultimately the Arrow time types are going to be done away with entirely, and instead the array will be a view of the underlying data which automatically returns Julia `Dates` types as elements.

**Comment by metanoid** [comment]
Okay, perfect, so for now I can convert all `Arrow.Datestamp` arrays to `Dates.Date` upfront!
