### ISSUE TITLE
behavior of `getindex` for `DictEncoding`

### ISSUE THREAD

**Issue by ExpandingMan** [ExpandingMan/Arrow.jl#7]
Initially my intent was the a `DictEncoding` would always return values normally (i.e. as individual elements or `Vector`s) and that it would be up to the user to convert it to `CategoricalArray`.  This may not be ideal.

I think my preferred option would be to retain this behavior, but have a special indexing function which constructs a `CategoricalArray` from slices.

Suggestions welcome.

**Comment by ExpandingMan** [comment]
For the time being we provide `categorical(A::DictEncoding)`, `categorical(A::DictEncoding, idx::AbstractVector{<:Integer})` and `convert(::Type{CategoricalArray}, A::DictEncoding)`.  This allows users to convert either the whole `DictEncoding` or arbitrary slices back to `CategoricalArray`.  Note that right now even slices copy the entire "pool" (levels, whatever the hell it's called).  This is probably not ok.

The behavior of `getindex` is the same as before, except for `getindex(A::DictEncoding, ::Colon)` which automatically converts to a `CategoricalArray`.

**Comment by sglyon** [comment]
> The behavior of getindex is the same as before, except for getindex(A::DictEncoding, ::Colon) which automatically converts to a CategoricalArray.

Does this mean that `Feather.materialize` will use CategoricalArray?

**Comment by ExpandingMan** [comment]
Right now yes.  I'm going to clean up `Feather.materalize` so that it will be a little more immune to the `getindex` semantics of Arrow.jl, but I will keep it so that if you `materialize` the whole table that it gives you a `CategoricalArray`.

I suppose that for `materialize` of slices it might also make sense to do `categorical` by default.  The reason I did not want to change `getindex` is because I wanted to make sure there was a way to get the values out without constructing a `CategoricalArray` and I didn't want to go through that heavy process by default when `getindex` can be used for all sorts of purposes.

**Comment by sglyon** [comment]
Those are great goals. I think getting a Julia value back when rows indexing with integers makes the most sense (either `df[i, j]` or `df[j, :]`)

**Comment by ExpandingMan** [comment]
I think I'm happy with the current behavior, so I'm going to close this issue for now.

If anyone has any objections to the use of `categorical` for this or the default behavior of `getindex`, please comment here, I'll re-open and we can reconsider.
