### ISSUE TITLE
consistent `getindex` semantics

### ISSUE THREAD

**Issue by ExpandingMan** [ExpandingMan/Arrow.jl#8]
When I first created this package my initial thinking was that `getindex` should create views wherever possible because "why not?".  `unsafe_wrap` seemed basically free.  Anyway, I now see that this was a bit crazy for several reasons.  I propose the following changes, which I will likely implement soon.

- `getindex` for scalars returns scalars just as it always has.
- [x] `getindex` creates new `Vector`s with copied data, always.  This is consistent with the behavior of `Vector`.
- [x] `view` always returns `SubArray` just as it does for other `AbstractVector`s.  No `view` function will be defined in Arrow.jl.
- [ ] `arrowview` will create an appropriate `ArrowVector` for the requested view.  This will only be possible for contiguous views.  I haven't worked out how this will work with `AbstractList` yet, but it should be relatively straightforward for `AbstractPrimitive`.

**Comment by ExpandingMan** [comment]
Sorry, I should have included that: of course nothing will change for scalars.  The relevant stuff here is for calling `getindex` with `AbstractVector{<:Integer}`.

My problem was that I would always attempt to cheat and return `unsafe_wrap`ed arrays for contiguous slices.  Besides being very confusing (you'd always get a disguised view for contiguous slices but deep copies for non-contiguous ones) this was very dangerous as I've explained [here](https://github.com/davidanthoff/FeatherLib.jl/issues/3).  Essentially what I'm going to do is use `unsafe_wrap` only within `unsafe_getvalue` functions which will in turn copy that data into a newly allocated `Vector`.  Since `unsafe_wrap` is essentially free, this should still be pretty much as efficient as it's possible to be while still doing a deep copy which is required here and consistent with the behavior of `Vector`.  You can still take `view`s just as you would with any other `AbstractArray`, only it won't lie to you and give you a bonified `SubArray`.

**Comment by davidanthoff** [comment]
Alright, that sounds great.

**Comment by ExpandingMan** [comment]
I've implemented `arrowview` for `Primitive` but I'm putting off the rest as it's a little complicated and doesn't seem like a priority at the moment.  Moving that to issue #23.  Closing this since `getindex` and `view` now work as intended.
